DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://distracted-torvalds-75fca5.netlify.com"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "gohugo-theme-ananke"
title = "Notre-Dame de Paris"
[params]
background_color_class = "bg-black"
custom_css = ["css/custom.css"]
description = "The last theme you'll ever need. Maybe."
facebook = ""
favicon = ""
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
github = ""
gitlab = ""
instagram = ""
linkedin = ""
mastodon = ""
recent_posts_number = 2
twitter = "https://twitter.com/GoHugoIO"
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
