DefaultContentLanguage = "sv"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = ""
baseURL = "https://distracted-torvalds-75fca5.netlify.com"
enableRobotsTXT = false
googleAnalytics = ""
languageCode = "sv-SE"
theme = "gohugo-theme-ananke"
title = "Laser Manufaktur"
[params]
background_color_class = "bg-black"
custom_css = ["css/custom.css"]
description = "Kreativ teknik"
facebook = "https://www.facebook.com/lazermanufaktur/"
favicon = "uploads/favicon-32x32.png"
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
github = ""
gitlab = ""
instagram = "https://instagram.com/lazermanufaktur"
linkedin = ""
mastodon = ""
recent_copy = "Senaste artiklarna"
recent_posts_number = 2
twitter = ""
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
