---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/image_gallery.json
  label: Images
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: content/post
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post-template
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  exclude: post/**/*
  templates:
  - page-template
- type: heading
  label: Image gallery
- type: document
  path: data/image_gallery.json
  label: Images
  templates:
  - item-template
- type: heading
  label: Settings
- type: document
  path: config.toml
  label: Site settings
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
